#Deploy Spring Boot WAR to Tomcat Docker Container
#==================================================
version: '3.8'
services:
  tomcat:
    image: tomcat:latest
    container_name: tomcat
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SGW_CLIENT_DIR=/tmp
    volumes:
      - ./target:/usr/local/tomcat/webapps
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3

#Deploy JAR to Docker Container - create a Dockerfile and put in its:
#==================================================
#FROM openjdk:17-slim
#ARG JAR_FILE=target/SgwClientFree.jar
#COPY ${JAR_FILE} /tmp
#EXPOSE 8080
#WORKDIR /tmp
#CMD java -jar SgwClientFree.jar --server.port=8080 -app.working.dir=/tmp
